"""initial schema

Revision ID: 2ceef015ec09
Revises:
Create Date: 2026-08-27 10:26:57.656446

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ceef015ec09"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("agent_did", sa.String(length=200), nullable=False),
        sa.Column("operator", sa.String(length=200), nullable=False),
        sa.Column("public_key", sa.Text(), nullable=False),
        sa.Column("trust_tier", sa.String(length=32), nullable=False),
        sa.Column("max_txn_paise", sa.BigInteger(), nullable=False),
        sa.Column("daily_cap_paise", sa.BigInteger(), nullable=False),
        sa.Column("registered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("agent_did"),
    )
    op.create_table(
        "gate_decisions",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("cart_id", sa.String(length=32), nullable=True),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("reason_code", sa.String(length=64), nullable=False),
        sa.Column("rule_id", sa.String(length=8), nullable=True),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("remedy", sa.Text(), nullable=False),
        sa.Column("evaluated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ledger_events",
        sa.Column("event_id", sa.String(length=32), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("session_id", sa.String(length=64), nullable=False),
        sa.Column("agent_did", sa.String(length=200), nullable=True),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("prev_hash", sa.String(length=64), nullable=False),
        sa.Column("chain_hash", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        op.f("ix_ledger_events_session_id"), "ledger_events", ["session_id"], unique=False
    )
    op.create_table(
        "merchants",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("did", sa.String(length=200), nullable=False),
        sa.Column("public_key", sa.Text(), nullable=False),
        sa.Column("private_key_enc", sa.Text(), nullable=False),
        sa.Column("whatsapp_number", sa.String(length=32), nullable=False),
        sa.Column("onboarding_state", sa.String(length=32), nullable=False),
        sa.Column("agent_policy", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("did"),
        sa.UniqueConstraint("whatsapp_number"),
    )
    op.create_table(
        "intent_envelopes",
        sa.Column("envelope_id", sa.String(length=32), nullable=False),
        sa.Column("user_ref", sa.String(length=200), nullable=False),
        sa.Column("user_whatsapp", sa.String(length=32), nullable=False),
        sa.Column("merchant_id", sa.String(length=32), nullable=False),
        sa.Column("agent_did", sa.String(length=200), nullable=False),
        sa.Column("ceiling_paise", sa.BigInteger(), nullable=False),
        sa.Column("spent_paise", sa.BigInteger(), nullable=False),
        sa.Column("max_single_txn_paise", sa.BigInteger(), nullable=False),
        sa.Column("allowed_categories", sa.JSON(), nullable=False),
        sa.Column("min_reversibility", sa.Float(), nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("signature", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("envelope_id"),
    )
    op.create_table(
        "products",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("merchant_id", sa.String(length=32), nullable=False),
        sa.Column("sku", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("category_class", sa.String(length=32), nullable=False),
        sa.Column("unit_price_paise", sa.BigInteger(), nullable=False),
        sa.Column("stock", sa.Integer(), nullable=True),
        sa.Column("return_window_days", sa.Integer(), nullable=True),
        sa.Column("fulfilment_hours", sa.Integer(), nullable=True),
        sa.Column("restocking_cost_pct", sa.Float(), nullable=False),
        sa.Column("is_personalised", sa.Boolean(), nullable=False),
        sa.Column("field_confidence", sa.JSON(), nullable=False),
        sa.Column("needs_review", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("source_media_url", sa.Text(), nullable=True),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "whatsapp_messages",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("merchant_id", sa.String(length=32), nullable=True),
        sa.Column("direction", sa.String(length=8), nullable=False),
        sa.Column("wa_message_id", sa.String(length=64), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("media_urls", sa.JSON(), nullable=False),
        sa.Column("intent", sa.String(length=64), nullable=True),
        sa.Column("handled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cart_mandates",
        sa.Column("cart_id", sa.String(length=32), nullable=False),
        sa.Column("envelope_id", sa.String(length=32), nullable=False),
        sa.Column("agent_did", sa.String(length=200), nullable=False),
        sa.Column("items", sa.JSON(), nullable=False),
        sa.Column("subtotal_paise", sa.BigInteger(), nullable=False),
        sa.Column("tax_paise", sa.BigInteger(), nullable=False),
        sa.Column("total_paise", sa.BigInteger(), nullable=False),
        sa.Column("reversibility_score", sa.Float(), nullable=False),
        sa.Column("reversibility_breakdown", sa.JSON(), nullable=False),
        sa.Column("band", sa.String(length=16), nullable=False),
        sa.Column("merchant_sig", sa.Text(), nullable=True),
        sa.Column("agent_sig", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["envelope_id"],
            ["intent_envelopes.envelope_id"],
        ),
        sa.PrimaryKeyConstraint("cart_id"),
    )
    op.create_table(
        "quotes",
        sa.Column("quote_id", sa.String(length=32), nullable=False),
        sa.Column("product_id", sa.String(length=32), nullable=False),
        sa.Column("agent_did", sa.String(length=200), nullable=False),
        sa.Column("unit_price_paise", sa.BigInteger(), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("total_paise", sa.BigInteger(), nullable=False),
        sa.Column("stock_held", sa.Boolean(), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("nonce", sa.String(length=64), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("signature", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("quote_id"),
        sa.UniqueConstraint("nonce"),
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("cart_id", sa.String(length=32), nullable=False),
        sa.Column("razorpay_order_id", sa.String(length=64), nullable=True),
        sa.Column("razorpay_payment_id", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column("cooling_off_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refunded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stepup_token", sa.String(length=64), nullable=True),
        sa.Column("stepup_confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stepup_channel", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["cart_id"],
            ["cart_mandates.cart_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orders")
    op.drop_table("quotes")
    op.drop_table("cart_mandates")
    op.drop_table("whatsapp_messages")
    op.drop_table("products")
    op.drop_table("intent_envelopes")
    op.drop_table("merchants")
    op.drop_index(op.f("ix_ledger_events_session_id"), table_name="ledger_events")
    op.drop_table("ledger_events")
    op.drop_table("gate_decisions")
    op.drop_table("agents")
    # ### end Alembic commands ###
