"""add order pending_gate_request and created_at

Revision ID: 8584d39d082d
Revises: 2ceef015ec09
Create Date: 2026-08-27 14:59:15.423863

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8584d39d082d"
down_revision: str | Sequence[str] | None = "2ceef015ec09"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("pending_gate_request", sa.JSON(), nullable=True))
    op.add_column("orders", sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "created_at")
    op.drop_column("orders", "pending_gate_request")
    # ### end Alembic commands ###
